# === VPC-level metadata ===
project_id: "my-gcp-project"
vpc_name: "vpc-b"

# === Per-region definitions ===
regions:
  europe-west3:
    routers:
      router-5:
        cloud_nats:
          - name: nat1
            address_count: 3
            min_ports_per_vm: 32
            enable_endpoint_independent_mapping: true
            enable_dynamic_port_allocation: false
            log_enable: true
            log_filter: "TRANSLATIONS_ONLY"
            source_subnetwork_ip_ranges_to_nat: "ALL_SUBNETWORKS_ALL_IP_RANGES"
